version: '3.4'

services:

  elastic:
    image: elastic
    hostname: elastic
    container_name: elastic
    build:
      context: ./DockerFiles/Elasticsearch
      dockerfile: Dockerfile
    expose:
      - 9200
      - 9300
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - ./DockerShared/ElasticSearch:/data
    networks:
      - spark

  elastic-ui:
    image: elastichq/elasticsearch-hq
    hostname: elastic-ui
    container_name: elastic-ui
    depends_on:
      - elastic
    ports:
      - 5000:5000
    networks:
      - spark

  spark-master:
    container_name: spark-master
    image: spark
    build:
      context: ./DockerFiles/Spark
      dockerfile: Dockerfile
    command: /spark/bin/spark-class org.apache.spark.deploy.master.Master -h spark-master
    hostname: spark-master
    environment:
      MASTER: spark://spark-master:7077
      SPARK_CONF_DIR: /conf
      SPARK_PUBLIC_DNS: localhost
    expose:
      - 7001
      - 7002
      - 7003
      - 7004
      - 7005
      - 7006
      - 7077
      - 6066
    ports:
      - 4040:4040
      - 6066:6066
      - 7077:7077
      - 8080:8080
    networks:
      - spark
    volumes:
      - ./DockerShared/Spark/conf/master:/conf
      - ./DockerShared/Spark/data:/tmp/data
  
  spark-worker1:
    image: spark
    container_name: spark-worker1
    command: /spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    hostname: spark-worker1
    environment:
      SPARK_CONF_DIR: /conf
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 1g
      SPARK_WORKER_PORT: 8881
      SPARK_WORKER_WEBUI_PORT: 8081
      SPARK_PUBLIC_DNS: localhost
    expose:
      - 7012
      - 7013
      - 7014
      - 7015
      - 7016
      - 8881
    ports:
      - 8081:8081
    volumes:
      - ./DockerShared/Spark/conf/worker:/conf
      - ./DockerShared/Spark/data:/tmp/data
    links:
      - spark-master
    networks:
      - spark
    depends_on:
      - spark-master

  spark-worker2:
    image: spark
    container_name: spark-worker2
    command: /spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    hostname: spark-worker2
    environment:
      SPARK_CONF_DIR: /conf
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 1g
      SPARK_WORKER_PORT: 8881
      SPARK_WORKER_WEBUI_PORT: 8082
      SPARK_PUBLIC_DNS: localhost
    expose:
      - 7012
      - 7013
      - 7014
      - 7015
      - 7016
      - 8881
    ports:
      - 8082:8082
    volumes:
      - ./DockerShared/Spark/conf/worker:/conf
      - ./DockerShared/Spark/data:/tmp/data
    links:
      - spark-master
    networks:
      - spark
    depends_on:
      - spark-master

  redis:
    image: 'bitnami/redis:latest'
    container_name: redis
    hostname: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
    volumes:
      - ./DockerShared/Redis/persistence:/bitnami/redis/data
    networks:
      - spark
    depends_on:
      - spark-master
  
  api:
    image: api
    hostname: api
    container_name: api
    build:
      context: ./api
      dockerfile: ../Dockerfiles/Api/DockerFile
    ports:
      - 6060:6060
    links:
      - elastic
      - redis
      - spark-master
    depends_on:
      - elastic
      - spark-master
      - redis
    networks:
      - spark
  
networks:
  spark:
    driver: bridge
    